import React, { useEffect, useMemo, useState } from 'react';
import { Alert, KeyboardAvoidingView, Modal, Platform, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { BowelEntry, CycleEntry, EntryKind, HealthStore, MealEntry, MedicationEntry, ObservationEntry, SymptomEntry } from './types';
import { severityWord } from './analysis';

type Editable = MealEntry | SymptomEntry | BowelEntry | CycleEntry | ObservationEntry | MedicationEntry;
type Props = {
  visible: boolean;
  kind?: Exclude<EntryKind, 'metric'>;
  entry?: Editable | null;
  onClose: () => void;
  onSave: (kind: Exclude<EntryKind, 'metric'>, entry: Editable) => void;
  onDelete: (kind: Exclude<EntryKind, 'metric'>, id: string) => void;
  onDuplicateMeal?: (meal: MealEntry) => void;
};

function datePart(iso: string) { const d = new Date(iso); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function timePart(iso: string) { const d = new Date(iso); return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`; }
function mergeDateTime(date: string, time: string, fallback: string) { const x = new Date(`${date}T${time}:00`); return Number.isNaN(x.getTime()) ? fallback : x.toISOString(); }
function level(value?: number) { return value == null ? '' : String(value); }
function setNum(value: string) { const n = Number(value.replace(',','.')); return Number.isFinite(n) ? Math.max(0, Math.min(10, n)) : undefined; }

export function findEntry(store: HealthStore, kind: Exclude<EntryKind,'metric'>, id: string): Editable | undefined {
  if (kind === 'meal') return store.meals.find(x=>x.id===id);
  if (kind === 'symptom') return store.symptoms.find(x=>x.id===id);
  if (kind === 'bowel') return store.bowel.find(x=>x.id===id);
  if (kind === 'cycle') return store.cycle.find(x=>x.id===id);
  if (kind === 'medication') return store.medications.find(x=>x.id===id);
  return store.observations.find(x=>x.id===id);
}

export default function EntryEditorModal({ visible, kind, entry, onClose, onSave, onDelete, onDuplicateMeal }: Props) {
  const [draft, setDraft] = useState<Editable | null>(entry || null);
  const [date, setDate] = useState(entry ? datePart(entry.createdAt) : '');
  const [time, setTime] = useState(entry ? timePart(entry.createdAt) : '');
  useEffect(()=>{ setDraft(entry || null); if(entry){setDate(datePart(entry.createdAt));setTime(timePart(entry.createdAt));}},[entry,visible]);
  const title = useMemo(()=> kind==='meal'?'Mahlzeit':kind==='symptom'?'Körpergefühl':kind==='bowel'?'Stuhlgang':kind==='cycle'?'Zyklus':kind==='medication'?'Medikament / Supplement':'Beobachtung',[kind]);
  if (!draft || !kind) return null;
  const save = () => onSave(kind, { ...draft, createdAt: mergeDateTime(date,time,draft.createdAt) } as Editable);
  const remove = () => Alert.alert('Eintrag löschen?', 'Dieser Eintrag wird dauerhaft aus Noura entfernt.', [{text:'Abbrechen',style:'cancel'},{text:'Löschen',style:'destructive',onPress:()=>onDelete(kind,draft.id)}]);
  return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><SafeAreaView style={styles.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}>
    <View style={styles.header}><View><Text style={styles.title}>{title} bearbeiten</Text><Text style={styles.sub}>Zeitpunkt und Inhalt lassen sich jederzeit korrigieren.</Text></View><TouchableOpacity onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></TouchableOpacity></View>
    <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
      <View style={styles.card}><Text style={styles.label}>Wann war das?</Text><View style={styles.two}><TextInput value={date} onChangeText={setDate} placeholder="JJJJ-MM-TT" style={[styles.input,{flex:1}]} /><TextInput value={time} onChangeText={setTime} placeholder="HH:MM" style={[styles.input,{width:100}]} /></View><Text style={styles.hint}>Wichtig für zeitliche Zusammenhänge: Trage den tatsächlichen Zeitpunkt ein, auch wenn du erst später dokumentierst.</Text></View>
      {kind==='meal' && (()=>{const m=draft as MealEntry;return <View style={styles.card}><Text style={styles.label}>Mahlzeit</Text><Text style={styles.value}>{m.mealType}</Text>{m.foods.map((f,i)=><View key={f.id} style={styles.food}><TextInput value={f.name} onChangeText={v=>setDraft({...m,foods:m.foods.map((x,j)=>j===i?{...x,name:v}:x)})} style={[styles.input,{flex:1}]} /><TextInput value={f.amount||''} onChangeText={v=>setDraft({...m,foods:m.foods.map((x,j)=>j===i?{...x,amount:v||undefined}:x)})} placeholder="Menge" style={[styles.input,{width:95}]} /></View>)}<TextInput value={m.note||''} onChangeText={v=>setDraft({...m,note:v||undefined})} placeholder="Notiz" multiline style={styles.note} /><View style={styles.switchRow}><Text style={styles.rowTitle}>Als Favorit speichern</Text><Switch value={!!m.favorite} onValueChange={v=>setDraft({...m,favorite:v})} /></View>{onDuplicateMeal?<TouchableOpacity style={styles.secondary} onPress={()=>onDuplicateMeal(m)}><Text style={styles.secondaryText}>Diese Mahlzeit nochmal eintragen</Text></TouchableOpacity>:null}</View>})()}
      {kind==='symptom' && (()=>{const s=draft as SymptomEntry;const fields:Array<[keyof SymptomEntry,string]>=[['pain','Bauchschmerzen'],['bloating','Blähungen'],['nausea','Übelkeit'],['heartburn','Sodbrennen'],['energy','Energie'],['stress','Stress']];return <View style={styles.card}>{fields.map(([k,l])=><View key={String(k)} style={styles.editRow}><View style={{flex:1}}><Text style={styles.rowTitle}>{l}</Text><Text style={styles.hint}>{severityWord(s[k] as number|undefined)}</Text></View><TextInput value={level(s[k] as number|undefined)} onChangeText={v=>setDraft({...s,[k]:v===''?undefined:setNum(v)})} placeholder="–" keyboardType="decimal-pad" style={styles.numberInput} /></View>)}<TextInput value={s.temperature==null?'':String(s.temperature)} onChangeText={v=>setDraft({...s,temperature:v===''?undefined:Number(v.replace(',','.'))})} placeholder="Temperatur optional" keyboardType="decimal-pad" style={styles.input}/><TextInput value={s.note||''} onChangeText={v=>setDraft({...s,note:v||undefined})} placeholder="Notiz" multiline style={styles.note}/></View>})()}
      {kind==='bowel' && (()=>{const b=draft as BowelEntry;return <View style={styles.card}><Text style={styles.label}>Bristol-Typ</Text><TextInput value={String(b.bristolType)} onChangeText={v=>setDraft({...b,bristolType:Math.max(1,Math.min(7,Number(v)||4))})} keyboardType="number-pad" style={styles.input}/><View style={styles.switchRow}><Text style={styles.rowTitle}>Schleim beobachtet</Text><Switch value={!!b.mucus} onValueChange={v=>setDraft({...b,mucus:v})}/></View><View style={styles.switchRow}><Text style={styles.rowTitle}>Blut beobachtet</Text><Switch value={!!b.blood} onValueChange={v=>setDraft({...b,blood:v})}/></View><TextInput value={b.note||''} onChangeText={v=>setDraft({...b,note:v||undefined})} placeholder="Notiz" multiline style={styles.note}/></View>})()}
      {kind==='cycle' && (()=>{const c=draft as CycleEntry;return <View style={styles.card}><View style={styles.switchRow}><Text style={styles.rowTitle}>Periode / Blutung</Text><Switch value={c.bleeding} onValueChange={v=>setDraft({...c,bleeding:v})}/></View><TextInput value={c.cramps==null?'':String(c.cramps)} onChangeText={v=>setDraft({...c,cramps:v===''?undefined:setNum(v)})} placeholder="Krämpfe 0–10 (optional)" keyboardType="number-pad" style={styles.input}/><TextInput value={c.note||''} onChangeText={v=>setDraft({...c,note:v||undefined})} placeholder="Notiz" multiline style={styles.note}/></View>})()}
      {kind==='observation' && (()=>{const o=draft as ObservationEntry;return <View style={styles.card}><TextInput value={o.text} onChangeText={v=>setDraft({...o,text:v})} multiline style={styles.note}/></View>})()}
      {kind==='medication' && (()=>{const m=draft as MedicationEntry;return <View style={styles.card}><View style={styles.two}><TouchableOpacity onPress={()=>setDraft({...m,kind:'medication'})} style={[styles.secondary,{flex:1},m.kind==='medication'&&{backgroundColor:'#EAF4EC'}]}><Text style={styles.secondaryText}>Medikament</Text></TouchableOpacity><TouchableOpacity onPress={()=>setDraft({...m,kind:'supplement'})} style={[styles.secondary,{flex:1},m.kind==='supplement'&&{backgroundColor:'#EAF4EC'}]}><Text style={styles.secondaryText}>Supplement</Text></TouchableOpacity></View><TextInput value={m.name} onChangeText={v=>setDraft({...m,name:v})} placeholder="Name" style={styles.input}/><TextInput value={m.dose||''} onChangeText={v=>setDraft({...m,dose:v||undefined})} placeholder="Dosis optional" style={styles.input}/><TextInput value={m.note||''} onChangeText={v=>setDraft({...m,note:v||undefined})} placeholder="Notiz" multiline style={styles.note}/></View>})()}
      <TouchableOpacity style={styles.save} onPress={save}><Text style={styles.saveText}>Änderungen speichern</Text></TouchableOpacity><TouchableOpacity onPress={remove} style={styles.delete}><Text style={styles.deleteText}>Eintrag löschen</Text></TouchableOpacity>
    </ScrollView>
  </KeyboardAvoidingView></SafeAreaView></Modal>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F7F9'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:18,borderBottomWidth:1,borderBottomColor:'#E9E6EC'},title:{fontSize:23,fontWeight:'900',color:'#242329'},sub:{fontSize:11,color:'#817D86',marginTop:3},close:{width:36,height:36,borderRadius:18,backgroundColor:'#EEEAF0',alignItems:'center',justifyContent:'center'},closeText:{fontSize:23,color:'#4E4952'},content:{padding:18,paddingBottom:50,gap:12},card:{backgroundColor:'#FFF',borderRadius:20,padding:15,borderWidth:1,borderColor:'#E9E6EC',gap:10},label:{fontSize:11,fontWeight:'900',color:'#625D67'},input:{backgroundColor:'#F6F4F7',borderWidth:1,borderColor:'#E8E4EA',borderRadius:13,paddingHorizontal:12,paddingVertical:11,color:'#28252B',fontSize:13},note:{minHeight:86,textAlignVertical:'top',backgroundColor:'#F6F4F7',borderWidth:1,borderColor:'#E8E4EA',borderRadius:13,padding:12,color:'#28252B'},two:{flexDirection:'row',gap:8},hint:{fontSize:10.3,lineHeight:14,color:'#88838D'},value:{fontSize:14,fontWeight:'800',color:'#28252B'},food:{flexDirection:'row',gap:7},switchRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',minHeight:48},rowTitle:{fontSize:13.5,fontWeight:'800',color:'#302D33'},editRow:{flexDirection:'row',alignItems:'center',gap:10,minHeight:55,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#EEEAF0'},numberInput:{width:62,textAlign:'center',backgroundColor:'#F6F4F7',borderRadius:12,paddingVertical:9,fontWeight:'800'},save:{backgroundColor:'#4FA85B',borderRadius:16,padding:15,alignItems:'center'},saveText:{color:'#FFF',fontWeight:'900'},secondary:{borderRadius:14,padding:12,alignItems:'center',backgroundColor:'#F0ECF5'},secondaryText:{color:'#70558E',fontWeight:'800'},delete:{padding:12,alignItems:'center'},deleteText:{color:'#B94A42',fontWeight:'800'}});
