import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Image, Modal, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { FoodItem } from './types';
import { FoodSearchResult, searchFoodProducts } from './foodLookup';

const colors = { bg:'#F7F7F9', surface:'#FFF', text:'#242329', muted:'#7F7B86', purple:'#71558F', purpleSoft:'#F2ECF8', line:'#EAE7ED', red:'#B94A42' };
function uid(){return `food-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;}

export default function FoodSearchModal({ visible, onClose, onAdd }:{ visible:boolean; onClose:()=>void; onAdd:(food:FoodItem)=>void }) {
  const [query,setQuery]=useState(''); const [items,setItems]=useState<FoodSearchResult[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [amount,setAmount]=useState<Record<string,string>>({});
  const generation=useRef(0);
  useEffect(()=>{ if(!visible){setQuery('');setItems([]);setError('');setLoading(false);} },[visible]);
  useEffect(()=>{
    const q=query.trim(); const id=++generation.current;
    if(q.length<2){setItems([]);setLoading(false);setError('');return;}
    const timer=setTimeout(async()=>{setLoading(true);setError('');try{const found=await searchFoodProducts(q,14);if(id===generation.current){setItems(found);if(!found.length)setError('Nichts Passendes gefunden. Du kannst das Lebensmittel auch manuell eintragen.');}}catch(e){if(id===generation.current)setError(e instanceof Error?e.message:'Lebensmittelsuche gerade nicht erreichbar.');}finally{if(id===generation.current)setLoading(false)}},350);
    return()=>clearTimeout(timer);
  },[query]);

  const add=(p:FoodSearchResult)=>{const grams=Number((amount[p.barcode]||'').replace(',','.')); const kcal100=p.nutritionPer100g.kcal; const kcal=Number.isFinite(grams)&&grams>0&&kcal100!=null?Math.round(kcal100*grams/100):undefined; onAdd({id:uid(),name:p.name,brand:p.brand,amount:amount[p.barcode]?.trim()||p.servingSize||undefined,kcal,source:p.source,barcode:p.barcode,imageUrl:p.imageUrl,ingredients:p.ingredients,allergens:p.allergens,nutritionPer100g:p.nutritionPer100g});};
  return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><SafeAreaView style={styles.safe}><View style={styles.header}><View style={{flex:1}}><Text style={styles.kicker}>LEBENSMITTELSUCHE</Text><Text style={styles.title}>Was hast du gegessen?</Text></View><TouchableOpacity onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></TouchableOpacity></View><View style={styles.search}><Text style={styles.searchIcon}>⌕</Text><TextInput autoFocus value={query} onChangeText={setQuery} placeholder="z. B. Skyr, Banane, Vollkornbrot" placeholderTextColor="#9995A0" style={styles.input}/></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    {loading?<View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Suche Produkte …</Text></View>:null}
    {!!error&&!loading?<View style={styles.info}><Text style={styles.infoText}>{error}</Text></View>:null}
    {items.map(p=><View key={`${p.barcode}-${p.name}`} style={styles.card}><View style={styles.productRow}>{p.imageUrl?<Image source={{uri:p.imageUrl}} style={styles.image}/>:<View style={[styles.image,styles.imageFallback]}><Text>🍽️</Text></View>}<View style={{flex:1}}><Text numberOfLines={2} style={styles.productName}>{p.name}</Text><Text numberOfLines={1} style={styles.productMeta}>{[p.brand,p.quantity,p.nutritionPer100g.kcal!=null?`${Math.round(p.nutritionPer100g.kcal)} kcal / 100 g`:null].filter(Boolean).join(' · ')}</Text></View></View><View style={styles.addRow}><TextInput value={amount[p.barcode]||''} onChangeText={v=>setAmount(a=>({...a,[p.barcode]:v}))} placeholder="Menge in g (optional)" keyboardType="decimal-pad" style={styles.amount}/><TouchableOpacity accessibilityRole="button" accessibilityLabel={`${p.name} hinzufügen`} onPress={()=>add(p)} style={styles.add}><Text style={styles.addText}>Hinzufügen</Text></TouchableOpacity></View></View>)}
    {!query.trim()?<View style={styles.center}><Text style={styles.big}>⌕</Text><Text style={styles.productName}>Einfach Namen eintippen</Text><Text style={styles.muted}>Häufige Lebensmittel findest du auch offline. Verpackte Produkte ergänzt Noura über Open Food Facts. Eigene Gerichte kannst du anschließend speichern.</Text></View>:null}
  </ScrollView></SafeAreaView></Modal>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},header:{flexDirection:'row',alignItems:'center',padding:18,paddingBottom:10,gap:12},kicker:{fontSize:9.5,fontWeight:'900',letterSpacing:1,color:colors.purple},title:{fontSize:25,fontWeight:'900',color:colors.text,marginTop:3},close:{width:38,height:38,borderRadius:19,backgroundColor:'#ECEAF0',alignItems:'center',justifyContent:'center'},closeText:{fontSize:25,color:colors.text,marginTop:-2},search:{marginHorizontal:18,flexDirection:'row',alignItems:'center',gap:9,backgroundColor:colors.surface,borderRadius:18,borderWidth:1,borderColor:colors.line,paddingHorizontal:13},searchIcon:{fontSize:20,color:colors.muted},input:{flex:1,paddingVertical:13,fontSize:14,color:colors.text},content:{padding:18,paddingBottom:60,gap:10},center:{alignItems:'center',padding:28,gap:8},big:{fontSize:32},muted:{color:colors.muted,fontSize:11.5,lineHeight:17,textAlign:'center'},info:{backgroundColor:'#FFF6E5',borderRadius:16,padding:13},infoText:{color:'#7B6328',fontSize:11.5,lineHeight:16},card:{backgroundColor:colors.surface,borderRadius:20,borderWidth:1,borderColor:colors.line,padding:13,gap:11},productRow:{flexDirection:'row',gap:11,alignItems:'center'},image:{width:54,height:54,borderRadius:14,backgroundColor:'#F2F0F4'},imageFallback:{alignItems:'center',justifyContent:'center'},productName:{color:colors.text,fontSize:14,fontWeight:'800'},productMeta:{color:colors.muted,fontSize:10.5,marginTop:3},addRow:{flexDirection:'row',gap:8},amount:{flex:1,backgroundColor:'#F7F7F9',borderRadius:13,paddingHorizontal:11,paddingVertical:10,color:colors.text,fontSize:11.5},add:{backgroundColor:colors.purple,borderRadius:13,paddingHorizontal:13,justifyContent:'center'},addText:{color:'#FFF',fontSize:11,fontWeight:'900'}});
