import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Image, Modal, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { AIConfig, AIQuickDraft, generateMealPhotoDraft } from './ai';
import { FoodItem, MealType } from './types';

const c={bg:'#F7F7F9',surface:'#FFF',text:'#242329',muted:'#7F7B86',purple:'#71558F',purpleSoft:'#F2ECF8',line:'#EAE7ED',red:'#B94A42'};
function uid(){return `photo-food-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;}

export default function PhotoMealCaptureModal({visible,config,onClose,onConfirm}:{visible:boolean;config:AIConfig|null;onClose:()=>void;onConfirm:(foods:FoodItem[],mealType:MealType,photoUri?:string)=>void}){
 const [uri,setUri]=useState(''); const [base64,setBase64]=useState(''); const [mime,setMime]=useState('image/jpeg'); const [draft,setDraft]=useState<AIQuickDraft|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{if(!visible){setUri('');setBase64('');setDraft(null);setLoading(false);setError('');}},[visible]);
 const pick=async(camera:boolean)=>{setError('');try{const perm=camera?await ImagePicker.requestCameraPermissionsAsync():await ImagePicker.requestMediaLibraryPermissionsAsync();if(!perm.granted){setError(camera?'Kamerazugriff wurde nicht erlaubt.':'Fotozugriff wurde nicht erlaubt.');return;}const r=camera?await ImagePicker.launchCameraAsync({mediaTypes:['images'] as any,base64:true,quality:0.55}):await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'] as any,base64:true,quality:0.55});if(r.canceled||!r.assets?.[0])return;const a=r.assets[0];setUri(a.uri);setBase64(a.base64||'');setMime(a.mimeType||'image/jpeg');setDraft(null);if(!a.base64){setError('Das Foto konnte nicht für die KI vorbereitet werden.');return;}if(!config){setError('Verbinde zuerst deine eigene KI, damit Noura das Foto auswerten kann.');return;}setLoading(true);try{setDraft(await generateMealPhotoDraft(config,a.base64,a.mimeType||'image/jpeg'));}catch(e){setError(e instanceof Error?e.message:'Foto konnte nicht ausgewertet werden.');}finally{setLoading(false)}}catch(e){setError(e instanceof Error?e.message:'Foto konnte nicht geöffnet werden.');}};
 const updateFood=(i:number,key:'name'|'amount',value:string)=>setDraft(d=>d?.meal?({...d,meal:{...d.meal,foods:d.meal.foods.map((x,j)=>j===i?{...x,[key]:value}:x)}}):d);
 const confirm=()=>{if(!draft?.meal?.foods?.length)return;onConfirm(draft.meal.foods.map(x=>({id:uid(),name:x.name.trim(),amount:x.amount?.trim()||undefined,source:'photo-ai'})).filter(x=>x.name),draft.meal.mealType,uri||undefined);onClose();};
 return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><SafeAreaView style={s.safe}><View style={s.header}><View style={{flex:1}}><Text style={s.kicker}>FOTO-EINGABE</Text><Text style={s.title}>Mahlzeit fotografieren</Text></View><TouchableOpacity onPress={onClose} style={s.close}><Text style={s.closeText}>×</Text></TouchableOpacity></View><ScrollView contentContainerStyle={s.content}>
  {!uri?<><View style={s.hero}><Text style={s.heroIcon}>📷</Text><Text style={s.heroTitle}>Foto → Vorschlag → bestätigen</Text><Text style={s.heroText}>Noura schlägt nur sichtbar erkennbare Lebensmittel vor. Mengen sind immer Schätzungen und bleiben änderbar.</Text></View><TouchableOpacity onPress={()=>pick(true)} style={s.primary}><Text style={s.primaryText}>Kamera öffnen</Text></TouchableOpacity><TouchableOpacity onPress={()=>pick(false)} style={s.secondary}><Text style={s.secondaryText}>Foto auswählen</Text></TouchableOpacity></>:<>
    <Image source={{uri}} style={s.photo}/>{loading?<View style={s.loading}><ActivityIndicator/><Text style={s.muted}>Noura schaut sich die Mahlzeit an …</Text></View>:null}{error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}
    {draft?.meal?<View style={s.card}><Text style={s.cardTitle}>Vorschlag prüfen</Text><Text style={s.muted}>{draft.understood}</Text>{draft.meal.foods.map((f,i)=><View key={i} style={s.foodRow}><TextInput value={f.name} onChangeText={v=>updateFood(i,'name',v)} style={[s.input,{flex:1}]} placeholder="Lebensmittel"/><TextInput value={f.amount||''} onChangeText={v=>updateFood(i,'amount',v)} style={[s.input,{width:110}]} placeholder="Menge"/></View>)}<TouchableOpacity onPress={confirm} style={s.primary}><Text style={s.primaryText}>Zur Mahlzeit übernehmen</Text></TouchableOpacity></View>:null}
    <TouchableOpacity onPress={()=>pick(true)} style={s.secondary}><Text style={s.secondaryText}>Neues Foto</Text></TouchableOpacity>
  </>}
 </ScrollView></SafeAreaView></Modal>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:c.bg},header:{flexDirection:'row',alignItems:'center',gap:12,padding:18,paddingBottom:8},kicker:{color:c.purple,fontSize:9.5,fontWeight:'900',letterSpacing:1},title:{color:c.text,fontSize:25,fontWeight:'900',marginTop:3},close:{width:38,height:38,borderRadius:19,backgroundColor:'#ECEAF0',alignItems:'center',justifyContent:'center'},closeText:{fontSize:25,color:c.text,marginTop:-2},content:{padding:18,paddingBottom:50,gap:12},hero:{backgroundColor:c.purpleSoft,borderRadius:24,padding:20,alignItems:'center'},heroIcon:{fontSize:34},heroTitle:{color:c.text,fontSize:17,fontWeight:'900',marginTop:10},heroText:{color:c.muted,fontSize:11.5,lineHeight:17,textAlign:'center',marginTop:6},primary:{backgroundColor:c.purple,borderRadius:16,paddingVertical:14,alignItems:'center',marginTop:10},primaryText:{color:'#FFF',fontWeight:'900',fontSize:13},secondary:{backgroundColor:c.surface,borderRadius:16,paddingVertical:13,alignItems:'center',borderWidth:1,borderColor:c.line},secondaryText:{color:c.purple,fontWeight:'800',fontSize:12},photo:{height:260,width:'100%',borderRadius:22,backgroundColor:'#EEE'},loading:{alignItems:'center',gap:8,padding:18},muted:{color:c.muted,fontSize:11.5,lineHeight:16},error:{backgroundColor:'#FDECEA',borderRadius:15,padding:12},errorText:{color:c.red,fontSize:11.5,lineHeight:16},card:{backgroundColor:c.surface,borderRadius:22,borderWidth:1,borderColor:c.line,padding:15,gap:9},cardTitle:{color:c.text,fontSize:16,fontWeight:'900'},foodRow:{flexDirection:'row',gap:7},input:{backgroundColor:'#F7F7F9',borderRadius:12,paddingHorizontal:10,paddingVertical:9,color:c.text,fontSize:11.5}});
